#!/bin/sh

## Get OSD-Information
if [ -f /opt/config/osd.conf ]; then
	source /opt/config/osd.conf 2>/dev/null
	# Call setconf only if we have something to set, to avoid outputing error messages
	[ ${DISPLAY_AXIS} ] && AXIS=$(/usr/bin/motor -d u -s 0 | tail +5 | awk '{printf ("%s ",$0)}' | awk '{print "X="$2,"Y="$4}') && OSD=$(echo ${OSD} | sed -r "s/X=.*$/${AXIS}/")
	[ ! -z "${OSD}" ] && /usr/bin/setconf -k o -v "${OSD}" 2>/dev/null
	[ ! -z "${COLOR}" ] && /usr/bin/setconf -k c -v ${COLOR} 2>/dev/null
	[ ! -z "${SIZE}" ] && /usr/bin/setconf -k s -v ${SIZE} 2>/dev/null
	[ ! -z "${POSY}" ] && /usr/bin/setconf -k x -v ${POSY} 2>/dev/null
	[ ! -z "${FIXEDW}" ] && /usr/bin/setconf -k w -v ${FIXEDW} 2>/dev/null
	[ ! -z "${SPACE}" ] && /usr/bin/setconf -k p -v ${SPACE} 2>/dev/null
	[ ! -z "${FONTNAME}" ] && /usr/bin/setconf -k e -v ${FONTNAME} 2>/dev/null

else
	/usr/bin/setconf -k o -v ""
fi
