#!/bin/sh

PIDFILE="/run/debug-on-osd.pid"

status() {
	pid="$(cat "$PIDFILE" 2>/dev/null)"
	if [ "$pid" ]; then
		kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
	fi
}

start() {
	if [ -f ${PIDFILE} ]; then
		echo "Debug on OSD already running"
	else
		echo "Starting debug on OSD"
		/opt/scripts/debug-osd.sh &>/dev/null &
		echo "$!" >"$PIDFILE"
	fi
}

stop() {
	pid="$(cat "$PIDFILE" 2>/dev/null)"
	if [ "${pid}" ]; then
		kill "$pid" && rm "$PIDFILE"
		/usr/bin/setconf -k o -v ""
	fi
}

if [ $# -eq 0 ]; then
	start
else
	case $1 in start | stop | status)
		$1
		;;
	esac
fi
