#!/bin/sh

# Motion detection script

if [ -f /opt/config/motion.conf ] ; then
    . /opt/config/motion.conf 2>/dev/null

    setconf -k r -v ${region_of_interest} 2>/dev/null

    if [ "$motion_detection" = false ]; then
      setconf -k m -v -1 2>/dev/null
    else
      setconf -k m -v ${motion_sensitivity} 2>/dev/null
    fi

    setconf -k z -v ${motion_indicator_color} 2>/dev/null
    setconf -k t -v ${motion_tracking} 2>/dev/null
fi;
